<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Lexplosion.UI.WPF</RootNamespace>
    <AssemblyName>Lexplosion</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>Lexplosion.UI.WPF.RuntimeApp</StartupObject>
    <ApplicationIcon>Assets\images\icons\logo.ico</ApplicationIcon>
    <AssemblyVersion>1.0.3.6</AssemblyVersion>
    <FileVersion>1.0.3.6</FileVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Core\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*.png" />
    <Resource Include="Assets\**\*.jpg" />
    <Resource Include="Assets\**\*.ico" />
    <Resource Include="Assets\**\*.ttf" />
    <Resource Include="Assets\**\*.otf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Libraries\Compression.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="Resources\Libraries\*.zip" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.VisualBasic" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" />
    <PackageReference Include="MarkdownWPF" />
    <PackageReference Include="MarkdownWPF.Html" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
    <PackageReference Include="VirtualizingWrapPanel" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexplosion.Core\Lexplosion.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="CopyCoreZip" BeforeTargets="PreBuildEvent">
    <Copy SourceFiles="$(SolutionDir)DLL\Lexplosion.Core.zip" DestinationFolder="$(ProjectDir)Resources\Libraries" SkipUnchangedFiles="true" />
  </Target>
</Project>