<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Lexplosion</RootNamespace>
    <AssemblyName>Lexplosion.Core</AssemblyName>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LumiSoft.Net" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Tommy" />
  </ItemGroup>

  <Target Name="ArchiveCore" AfterTargets="Build">
    <Exec Command="powershell -Command &quot;New-Item -ItemType Directory -Force -Path '$(SolutionDir)DLL'; Compress-Archive -Path '$(TargetPath)' -DestinationPath '$(SolutionDir)DLL\Lexplosion.Core.zip' -Force&quot;" />
  </Target>
</Project>